import type { Study } from "../utils/tipos"

export const mockStudies: Study[] = [
  {
    id: "LAB-2025-001",
    patientName: "María González",
    study: "Seros",
    date: "2025-01-15",
    status: "Completado",
    doctor: "Dr. Carlos Ramírez",
  },
  {
    id: "LAB-2025-002",
    patientName: "Juan Pérez",
    study: "Osde",
    date: "2025-01-18",
    status: "Completado",
    doctor: "Dra. Ana Martínez",
  },
  {
    id: "LAB-2025-003",
    patientName: "Carmen López",
    study: "Ospecon",
    date: "2025-01-20",
    status: "Parcial",
    doctor: "Dr. Luis Torres",
  },
  {
    id: "LAB-2025-004",
    patientName: "Roberto Sánchez",
    study: "Avalian",
    date: "2025-01-22",
    status: "Completado",
    doctor: "Dra. Patricia Ruiz",
  },
  {
    id: "LAB-2025-005",
    patientName: "Laura Fernández",
    study: "Seros",
    date: "2025-01-25",
    status: "En Proceso",
    doctor: "Dr. Miguel Ángel Castro",
  },
  {
    id: "LAB-2025-006",
    patientName: "Diego Morales",
    study: "Swiss medical",
    date: "2025-02-01",
    status: "Completado",
    doctor: "Dr. Carlos Ramírez",
  },
  {
    id: "LAB-2025-007",
    patientName: "Sofía Vargas",
    study: "Osde",
    date: "2025-02-05",
    status: "Completado",
    doctor: "Dra. Elena Jiménez",
  },
  {
    id: "LAB-2025-008",
    patientName: "Andrés Rojas",
    study: "Osde",
    date: "2025-02-08",
    status: "Parcial",
    doctor: "Dr. Luis Torres",
  },
  {
    id: "LAB-2025-009",
    patientName: "Valentina Cruz",
    study: "Sancor Salud",
    date: "2025-02-10",
    status: "Completado",
    doctor: "Dra. Ana Martínez",
  },
  {
    id: "LAB-2025-010",
    patientName: "Fernando Díaz",
    study: "Osde",
    date: "2025-02-12",
    status: "En Proceso",
    doctor: "Dr. Carlos Ramírez",
  },
]
